const classRouter = [
  {
    title: '进入班级',
    type: 'view',
    name: null,
    route: '/class/list',
    filePath: 'view/class/class-list.vue',
    inNav: true,
    icon: 'iconfont icon-erji1',
    order: 3,
    permission: ['查询学生本学期所属班级'],
  },
  {
    title: '进入班级（教师）',
    type: 'view',
    name: null,
    route: '/teacher/class/list',
    filePath: 'view/teacher/class/class-list.vue',
    inNav: true,
    icon: 'iconfont icon-erji1',
    order: 4,
    permission: ['查询教师本学期所属班级'],
  },
  {
    title: '班级页面（学生）',
    type: 'tab',
    name: Symbol('room'),
    // route: '/class/room/work',
    // filePath: 'view/class/room/work-list.vue',
    inNav: false,
    icon: 'anticon icon-home',
    children: [
      {
        route: '/class/room/work',
        type: 'view',
        name: Symbol('workList'),
        filePath: 'view/class/room/work-list.vue',
        inNav: true,
        title: '作业列表',
        icon: 'iconfont icon-kecheng',
      },
      {
        route: '/class/room/announce',
        type: 'view',
        name: Symbol('announceList'),
        filePath: 'view/class/room/announce-list.vue',
        inNav: true,
        title: '公告列表',
        icon: 'anticon icon-book',
      },
      {
        route: '/class/room/questionnaire',
        type: 'view',
        name: Symbol('questionnaireList'),
        filePath: 'view/class/room/questionnaire-list.vue',
        inNav: true,
        title: '问卷列表',
        icon: 'anticon icon-profile',
      },
    ],
  },
  {
    title: '班级页面（教师）',
    type: 'tab',
    name: Symbol('teacher-room'),
    // route: '/teacher/class/room/work',
    // filePath: 'view/teacher/class/room/work-list.vue',
    inNav: false,
    icon: 'anticon icon-home',
    children: [
      {
        route: '/teacher/class/room/sign',
        type: 'view',
        name: Symbol('signList'),
        inNav: true,
        filePath: 'view/teacher/class/room/sign-list.vue',
        title: '签到列表',
        icon: 'iconfont icon-jiemianicon-',
        permission: ['查看所有签到项目'],
      },
      {
        route: '/teacher/class/room/work',
        type: 'view',
        name: Symbol('workList'),
        filePath: 'view/teacher/class/room/work-list.vue',
        inNav: true,
        title: '作业列表',
        icon: 'iconfont icon-kecheng',
        permission: ['查看所有作业项目'],
      },
      {
        route: '/teacher/class/room/announce',
        type: 'view',
        name: Symbol('announceList'),
        filePath: 'view/teacher/class/room/announce-list.vue',
        inNav: true,
        title: '公告列表',
        icon: 'anticon icon-book',
        permission: ['查看所有通知公告'],
      },
      {
        route: '/teacher/class/room/questionnaire',
        type: 'view',
        name: Symbol('questionnaireList'),
        filePath: 'view/teacher/class/room/questionnaire-list.vue',
        inNav: true,
        title: '问卷列表',
        icon: 'anticon icon-profile',
        permission: ['查看所有问卷'],
      },
    ],
  },
  {
    title: '签到人员统计',
    type: 'view',
    name: null,
    route: '/teacher/class/room/sign/list/:id',
    filePath: 'view/teacher/class/room/sign-student-list.vue',
    inNav: false,
    icon: 'iconfont icon-huiyuanguanli',
    order: null,
    permission: ['查询单个签到项目下的所有学生'],
  },
  {
    title: '作业人员统计',
    type: 'view',
    name: null,
    route: '/teacher/class/room/work/list/:id',
    filePath: 'view/teacher/class/room/work-student-list.vue',
    inNav: false,
    icon: 'iconfont icon-huiyuanguanli',
    order: null,
    permission: ['查询单个作业项目下的所有学生'],
  },
  {
    title: '编辑通知公告',
    type: 'view',
    name: null,
    route: '/teacher/class/room/announce/edit/:id',
    filePath: 'view/teacher/class/room/announce-edit.vue',
    inNav: false,
    icon: 'anticon icon-form',
    order: null,
    permission: ['发布通知公告'],
  },
  {
    title: '查看通知公告',
    type: 'view',
    name: null,
    route: '/class/room/announce/view/:id',
    filePath: 'view/class/room/announce-view.vue',
    inNav: false,
    icon: 'anticon icon-form',
    order: null,
    permission: ['查看单个通知公告'],
  },
  {
    title: '编辑问卷',
    type: 'view',
    name: null,
    route: '/teacher/class/room/questionnaire/edit/:id',
    filePath: 'view/teacher/class/room/questionnaire-edit.vue',
    inNav: false,
    icon: 'anticon icon-form',
    order: null,
    permission: ['发布问卷'],
  },
  {
    title: '查看问卷',
    type: 'view',
    name: null,
    route: '/class/room/questionnaire/view/:id',
    filePath: 'view/class/room/questionnaire-view.vue',
    inNav: false,
    icon: 'anticon icon-form',
    order: null,
    permission: ['查看单个问卷'],
  },
]

export default classRouter
